### ISSUE TITLE
Forms & Overlay don't build in Ember v4

### ISSUE THREAD

**Issue by knownasilya** [josemarluedke/frontile#191]
Get this error

```
$ ember serve
Build Error (broccoli-persistent-filter:Babel > [Babel: @embroider/macros]) in @embroider/macros/runtime.js

/Users/ilya/maintained/bchess/@embroider/macros/runtime.js: @babel/template placeholder "APP": Expected string substitution


Stack Trace and Error Report: /var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/error.dump.0a1dce955e6458ce08af9c881bd0c487.log
```

Which seems to be caused by ember-element-helper:

```
Error: @babel/template placeholder "APP": Expected string substitution
        at applyReplacement (/Users/ilya/maintained/bchess/node_modules/@babel/template/lib/populate.js:74:13)
        at /Users/ilya/maintained/bchess/node_modules/@babel/template/lib/populate.js:44:7
        at Array.forEach (<anonymous>)
        at populatePlaceholders (/Users/ilya/maintained/bchess/node_modules/@babel/template/lib/populate.js:42:43)
        at /Users/ilya/maintained/bchess/node_modules/@babel/template/lib/string.js:20:51
        at /Users/ilya/maintained/bchess/node_modules/@babel/template/lib/builder.js:75:14
        at Object.buildLiterals (/Users/ilya/maintained/bchess/node_modules/ember-element-helper/node_modules/@embroider/macros/src/babel/evaluate-json.js:377:73)
        at Object.inlineRuntimeConfig (/Users/ilya/maintained/bchess/node_modules/ember-element-helper/node_modules/@embroider/macros/src/babel/get-config.js:107:55)
        at PluginPass.enter (/Users/ilya/maintained/bchess/node_modules/ember-element-helper/node_modules/@embroider/macros/src/babel/macros-babel-plugin.js:77:38)
        at newFn (/Users/ilya/maintained/bchess/node_modules/@babel/traverse/lib/visitors.js:177:21)
        =============
        at Object.buildLiterals (/Users/ilya/maintained/bchess/node_modules/ember-element-helper/node_modules/@embroider/macros/src/babel/evaluate-json.js:377:34)
        at Object.inlineRuntimeConfig (/Users/ilya/maintained/bchess/node_modules/ember-element-helper/node_modules/@embroider/macros/src/babel/get-config.js:107:55)
        at PluginPass.enter (/Users/ilya/maintained/bchess/node_modules/ember-element-helper/node_modules/@embroider/macros/src/babel/macros-babel-plugin.js:77:38)
        at newFn (/Users/ilya/maintained/bchess/node_modules/@babel/traverse/lib/visitors.js:177:21)
        at NodePath._call (/Users/ilya/maintained/bchess/node_modules/@babel/traverse/lib/path/context.js:53:20)
        at NodePath.call (/Users/ilya/maintained/bchess/node_modules/@babel/traverse/lib/path/context.js:40:17)
        at NodePath.visit (/Users/ilya/maintained/bchess/node_modules/@babel/traverse/lib/path/context.js:100:31)
        at TraversalContext.visitQueue (/Users/ilya/maintained/bchess/node_modules/@babel/traverse/lib/context.js:103:16) {
      code: 'BABEL_TRANSFORM_ERROR',
      file: '@embroider/macros/runtime.js',
      treeDir: '/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-19503Ykau1Heg5XG3/out-163-funnel_funnel_embroider_macros_addon'
```

Should be fixable once https://github.com/tildeio/ember-element-helper/pull/73 lands
Note that Overlays depend on Forms, that's why both are affected.

**Comment by josemarluedke** [comment]
This is a problem I'm seeing in several projects when having dependencies with Embroider < v1 and v1. So, I suggest adding resolutions to your package.json

```
  "resolutions": {
    "@embroider/macros": "^1.0.0",
    "@embroider/shared-internals": "^1.0.0",
    "@embroider/util": "^1.0.0"
  }
```

**Comment by josemarluedke** [comment]
Also, not sure why overlays is depending on forms. I will check that out and remove the dep.

**Comment by josemarluedke** [comment]
Removed the dependency here https://github.com/josemarluedke/frontile/pull/193
